apiVersion: v1
kind: Service
metadata:
  name: backend
  labels: 
    group: example
spec:
  selector: 
    app: second-app
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
    # - protocol: 'TCP'
    #   port: 443
    #   targetPort: 443
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app-deployment
  labels: 
    group: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second-app
      tier: backend
    # matchExpressions:
    #   - {key: app, operator: NotIn, values: [second-app, first-app]}
  template: 
    metadata:
      labels: 
        app: second-app
        tier: backend
    spec:
      containers: 
        - name: second-node
          image: arijaya130/kub-first-app:2
        # - name: ...
        #   image: ..